from . import it_asset_category
from . import it_asset_location
from . import it_amc
from . import it_asset
from . import it_asset_assignment
from . import it_asset_request
from . import it_asset_audit
from . import it_software_license
from . import it_consumable
from . import it_ticket
from . import purchase_order
from . import hr_employee
from . import maintenance_request
from . import res_config_settings
from . import account_move
